language: node_js
node_js:
  - '6'

before_install:
- npm i -g npm@3

cache:
  directories:
    - "node_modules"

deploy:
      - provider: s3
        ⋮ # rest of S3 deployment for MyApp.zip
      - provider: codedeploy
        access_key_id: "AKIAIBOP55MKHDDOWYCQ"
        bucket: "kmsquared"
        key: latest/MyApp.zip
        application: ThesisBackEnd
        region: us-east-2
        on: 2*

script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest/MyApp.zip dpl_cd_upload/latest/MyApp.zip