language: node_js
node_js:
  - '6'

before_install:
- npm i -g npm@3

cache:
  directories:
    - "node_modules"

before_deploy:
  - zip -r latest ThesisBackEnd.zip
  - mkdir -p "dpl_cd_upload"
  - mv ThesisBackEnd.zip dpl_cd_upload/ThesisBackEnd.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    bucket: kmsquared
    region: us-east-2
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: kmsquared
    key: ThesisBackEnd.zip
    bundle_type: zip
    application: ThesisBackEnd
    region: us-east-2
    on:
      repo: KMS-Squared/thesis
      all_branches: true

after_deploy:
  - echo "Performing after deploy procedures..."

notifications:
  email:
    recipients:
      - suyatdesign@gmail.com


